feat: общая структура проекта
DiNosauur/java-explore-with-me pull request #3
Opened 2022-11-15 21:05 UTC by DiNosauur

2022-12-04 20:04 UTC, kukolev requested changes

2022-12-04 20:04 UTC, kukolev commented on main-server/src/main/java/ru/practicum/ewm/user/dto/UserRequestDto.java
> +    @Email(regexp = "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$", //"\\w+@\\w+\\.(ru|com)",
Этот комментарий никак не помогает анализировать код. Бесполезные комментарии нужно удалять, чтобы не мешали.

2022-12-04 20:04 UTC, kukolev commented on main-server/src/main/resources/application.properties
> +#spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-12-04 20:04 UTC, kukolev commented on stats-server/src/main/resources/application.properties
> +#javax.persistence.schema-generation.database.action=create
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-12-04 20:04 UTC, kukolev commented on main-server/src/main/java/ru/practicum/ewm/event/EventClient.java
> +                "uris", String.join(",", uris), //uris.stream().collect(Collectors.joining(",")),
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-12-04 20:04 UTC, kukolev commented on main-server/src/main/resources/application.properties
> +#server.port=8081
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-12-04 20:24 UTC, DiNosauur commented on main-server/src/main/java/ru/practicum/ewm/user/dto/UserRequestDto.java
> +    @Email(regexp = "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$", //"\\w+@\\w+\\.(ru|com)",
Исправлено.

2022-12-04 20:24 UTC, DiNosauur commented on main-server/src/main/resources/application.properties
> +#spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
Исправлено.

2022-12-04 20:25 UTC, DiNosauur commented on stats-server/src/main/resources/application.properties
> +#javax.persistence.schema-generation.database.action=create
Исправлено.

2022-12-04 20:26 UTC, DiNosauur commented on main-server/src/main/java/ru/practicum/ewm/event/EventClient.java
> +                "uris", String.join(",", uris), //uris.stream().collect(Collectors.joining(",")),
Исправлено.

2022-12-04 20:27 UTC, DiNosauur commented on main-server/src/main/resources/application.properties
> +#server.port=8081
Исправлено.

2022-12-05 16:50 UTC, kukolev approved these changes

2022-12-05 18:38 UTC, merged